language: node_js
node_js:
  - '10.16.3'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH="$HOME/.yarn/bin:$PATH"
  - export NODE_OPTIONS=--max_old_space_size=4096

jobs:
  include:
    - stage: release
      node_js: '10.16.3'
      script:
        - yarn
        - yarn build:ci
        - yarn test
        - yarn semantic-release
